<?php

return [
    'RESPONSE_CONSTANTS' => [
        'STATUS_ERROR'=> 0,
        'STATUS_SUCCESS'=> 1,
        'STATUS_OTHER_ERROR'=> 2,
        'STATUS_ACCOUNT_UNAUTHORIZED'=> 3,
        'STATUS_ACCOUNT_SUSPENDED'=> 4,
        'STATUS_ACCOUNT_DELETED'=> 5,
        'STATUS_INVALID_TOKEN'=> 6,
        'STATUS_INVALID_USER_TYPE'=> 7,
        'STATUS_INVALID_COUPON_CODE'=> 8,
        'STATUS_INVALID_AVAILABLE_QUANTITY'=> 9,
        'STATUS_INVALID_PRODUCT_QUANTITY' => 10,
        'INVALID_PARAMETERS'=> 'Invalid Request Parameters.',
        'ERROR_EMAIL_EXIST'=> 'Email Already In Use.',
        'ERROR_PHONE_EXIST'=> 'Phone Already In Use.',
        'ERROR_USER_NAME_EXIST'=> 'User Name Already In Use.',
        'ERROR_INVALID_CREDENTIALS'=> 'Invalid Email or Password.',
        'ERROR_ACCOUNT_SUSPENDED'=> 'Your Account Has Been Suspended.',
        'ERROR_ACCOUNT_DELETED'=> 'Your Account Has Been Deleted.',
        'ERROR_ACCOUNT_UNAUTHORIZED'=> 'Your Account Is Not Authorized Yet.',
        'ERROR_INVALID_EMAIL'=> 'Invalid Email Address.',
        'ERROR_INVALID_USER_TYPE'=> 'Invalid User Type.',
        'ERROR_INVALID_COUPON_CODE'=> 'Invalid Coupon Code.',
        'MSG_LOGGED_IN'=> 'Logged In Successfully.',
        'MSG_REGISTERED_SUCCESS'=> 'Registered Successfully.',
        'MSG_REGISTERED_PROFESSIONAL'=> 'Registered Successfully. You can login once your account is approved.',
        'MSG_LOGGED_OUT' => 'Logged out successfully.',
        'KEY_PAGE_NO' => 'page_no',
        'KEY_RECORD_PER_PAGE' => 10,
    ],
    'ADDRESS_CONSTANTS' => [
        'KEY_ADDRESS_ID'=> 'address_id',
        'KEY_ADDRESS_TYPE'=> 'address_type',
        'KEY_CITY'=> 'city',
        'KEY_COUNTRY'=> 'country',
        'KEY_ADDRESS'=> 'address',
        'KEY_ADDRESSES'=> 'addresses',
    ],
    'CONSUMER_CONSTANTS' => [
        'KEY_CONSUMER_ID'=> 'consumer_id',
        'KEY_FULL_NAME'=> 'full_name',
        'KEY_EMAIL'=> 'email',
        'KEY_PASSWORD'=> 'password',
        'KEY_PHONE'=> 'phone',
        'KEY_PROFILE_IMAGE'=> 'profile_image',
        'KEY_DEVICE_ID'=> 'device_id',
        'KEY_DEVICE_TYPE' => 'device_type',
    ],
    'PROFESSIONAL_CONSTANTS' => [
        'KEY_PROFESSIONAL_ID'=> 'professional_id',
        'KEY_FULL_NAME'=> 'full_name',
        'KEY_EMAIL'=> 'email',
        'KEY_PASSWORD'=> 'password',
        'KEY_PHONE'=> 'phone',
        'KEY_PROFILE_IMAGE'=> 'profile_image',
        'KEY_COMPANY_NAME'=> 'company_name',
        'KEY_COMPANY_WEBSITE'=> 'company_website',
        'KEY_COMPANY_ADDRESS'=> 'company_address',
        'KEY_DEVICE_ID'=> 'device_id',
        'KEY_DEVICE_TYPE' => 'device_type',
    ],
    'CATEGORY_CONSTANTS' => [
        'KEY_CATEGORY_ID'=> 'category_id',
        'KEY_SUB_CATEGORY_ID'=> 'sub_category_id',
        'KEY_SUB_CHILD_CATEGORY_ID'=> 'sub_child_category_id'
    ],
    'FAVOURITE_CONSTANTS'=>[

        'KEY_PRODUCT_ID'=> 'product_id',
        'KEY_FAVOURITE_ID'=> 'favourite_id',
    ],
    'ORDER_CONSTANTS' => [
        'KEY_ORDER_ID'=> 'order_id',
        'KEY_GROSS_TOTAL'=> 'gross_total',
        'KEY_NET_TOTAL'=> 'net_total',
        'KEY_DISCOUNT_SLAB_ID'=> 'discount_slab_id',
        'KEY_DISCOUNT_AMOUNT'=> 'discount_amount',
        'KEY_COUPON_CODE'=> 'coupon_code',
        'KEY_COUPON_DISCOUNT_AMOUNT'=> 'coupon_discount_amount',
        'KEY_FIX_DISCOUNT' => 'fix_discount_amount',
        'KEY_DELIVERY_CHARGES' => 'delivery_charges',
        'KEY_SHIPPING_ADDRESS_ID'=> 'shipping_address_id',
        'KEY_PAYMENT_METHOD'=> 'payment_method',
        'KEY_PRODUCTS'=> 'products',
        'KEY_PRODUCT_QUANTITY'=> 'product_quantity',
        'KEY_PRODUCT_FRAME_COLOR'=> 'frame_color',
        'KEY_PRODUCT_LEFT_ENGRAVE'=> 'left_engrave',
        'KEY_PRODUCT_RIGHT_ENGRAVE'=> 'right_engrave',
        'KEY_PRODUCT_SIZE'=> 'size',
        'KEY_COLOR_ID'=> 'color_id',
        'KEY_ORDER_STATUS' => 'order_status',
        'KEY_ORDER_PAYMENT_STATUS' => 'payment_status',
        'KEY_PRODUCT_ID'=> 'product_id',
        'KEY_ADMIN_EMAIL' => 'admin_email',
        'KEY_DATE_FROM' => 'date_from',
        'KEY_DATE_TO' => 'date_to',
    ],
    'PRODUCT_CONSTANTS' => [
        'KEY_CATEGORY_ID' => 'category_id',
        'KEY_SUB_CATEGORY_ID' => 'sub_category_id',
        'KEY_SUB_CHILD_CATEGORY_ID' => 'sub_child_category_id',
    ],
    'GENERAL_CONSTANTS' => [
        'KEY_CONSUMER_ID'=> 'consumer_id',
        'KEY_PROFESSIONAL_ID'=> 'professional_id',
        'KEY_PAGE_NO'=> 'page_no',
        'KEY_PAGE_ID'=> 'page_id',
        'KEY_PRODUCT_ID'=> 'product_id',
        'KEY_COMMENT' => 'comment',
        'KEY_RATING' => 'rating',
    ],
];
